### ISSUE TITLE
Omnifactory Emeradic Empowered Gear encoding issues.

### ISSUE THREAD

**Issue by eutropius225** [OmnifactoryDevs/ExtendedCrafting#6]
Reportedly, Packaged Ex Crafting can't encode the recipe, but it works fine when not using this fork.

This is likely caused by some changes we have made that leave PExC unable find the recipe.

**Comment by Exaxxion** [comment]
The weird part is it's just the output item that doesn't get pasted in from JEI. For example with the Emeradic Gear, the ingredients paste in fine but the output doesn't set to the gear.
