### ISSUE TITLE
Quantum Compressor doesn't work sometimes unless broken & replaced

### ISSUE THREAD

**Issue by vizthex123** [OmnifactoryDevs/ExtendedCrafting#7]
Occasionally, it will just not craft anything (I only have recipes I added myself though, so that might be part of the issue?) until you break the block and replace it.

It's annoying since you lose all the RF stored (and in the early/mid-game I'm at, RF is somewhat hard to get)

No clue what's causing this bug though, but I hope you guys look into it.

**Comment by eutropius225** [comment]
Do you have any steps to reproduce the issue?

**Comment by vizthex123** [comment]
Just make some custom recipes, try to craft them, and see if it breaks.

Like I said, it's random and I have no clue what's causing it. Maybe it's caused by you using it, moving it far away, then trying to use it again? Kinda seems like that...?

If possible, a good workaround would be to make blocks retain energy when broken (maybe make it a config option?)

**Comment by Exaxxion** [comment]
Without any context and steps to reliably reproduce the issue, it's nearly impossible to solve your problem. If you are still encountering this problem and can elaborate, please do.

Retaining energy when breaking ExC items is probably feasible, but that would be a feature request to consider separately from this bug report.

**Comment by vizthex123** [comment]
It's kind of weird?

Seems to happen whenever you replace the catalyst without placing the item in your inventory first.

Honestly all I can describe, sorry.

**Comment by ferreiraalex** [comment]
> It's kind of weird?
> 
> Seems to happen whenever you replace the catalyst without placing the item in your inventory first.
> 
> Honestly all I can describe, sorry.

Ye! i have this problem? what you want? i did screenshots and my problem too like vizthex only if i replce catalyst its work

https://imgur.com/a/ciMC3mY

**Comment by ferreiraalex** [comment]
https://www.youtube.com/watch?v=r_EdDhq6fks
SEE THIS

**Comment by ferreiraalex** [comment]
Pleeease fix thus bug! bump

**Comment by Exaxxion** [comment]
It's not necessary to bump issues. Our attention is split between multiple projects so we aren't always able to fix things quickly, but we do keep track of what issues are still open and get to them when possible.

**Comment by eutro** [comment]
Again, if you can provide steps to reproduce the issue, or any context as to when it can happen, it would be immensely helpful.

**Comment by ferreiraalex** [comment]
i provide steps for you in video, i press shift click on catalisator he puts in slot for items, and after Quantum Compressor not eat items. This say  "vizthex123" and if i break the block and replace it and put catalisator to left slot manually Quantum Compressor work good i think its work with all non registry items for singularity. i think it is
